console.log("my first console project");
var name = "Rohini Arya";
console.log(name);
var a = 10;
var b = 5;
var add = a + b;
console.log(add);
var subtract = a - b;
console.log(subtract);
var multiplication = a * b;
console.log(multiplication);
var division = a / b;
console.log(division);